#!/bin/sh
read -p "Choose episode (1-13): " ep
url="https://api.consumet.org/anime/gogoanime/watch/serial-experiments-lain-episode-$ep"
referer=$(curl -sIL "$url" | awk '/^Referer:/ {print $2}')
mpv $(curl -s "$url" -G -d "server=gogocdn" | jq -r '.sources[] | select(.quality == "default") | .url') --http-header-fields="Referer: $referer"
